GRANT CREATE ON *.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'user'@'%';
CREATE USER 'root'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
