version: '3.8'

services:
  db:
    build: ./mysql  # Dockerfile でカスタマイズした MySQL をビルド
    container_name: my-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
      LC_ALL: ja_JP.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf  # MySQL 設定を適用
      - ./init:/docker-entrypoint-initdb.d  # 初期SQLをマウント]

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
